### ISSUE TITLE
grunt elasticsearch test

### ISSUE THREAD

**Issue by sieira** [linagora/openpaas-esn#1]
I'm trying to get an overview of the openpaas platform, and while running the grunt test for elasticsearch it fails.

Actually, my elasticsearch is installed from the elastic repos at https://www.elastic.co/guide/en/elasticsearch/reference/1.x/setup-repositories.html and my system (ubuntu vivid) uses sysV scripts to start elasticsearch (service elasticsearch start works without problem).

Trying to launch elasticsearch from the command line results in the failure traced here below :

    Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
    Failed to configure logging...
    org.elasticsearch.ElasticsearchException: Failed to load logging configuration
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:142)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:92)
	at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:131)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:216)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
    Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:126)
	... 4 more
    log4j:WARN No appenders could be found for logger (node).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
    {1.6.0}: Initialization Failed ...
    - ElasticsearchIllegalStateException[Failed to created node environment]
	AccessDeniedException[/usr/share/elasticsearch/data]
    org.elasticsearch.ElasticsearchIllegalStateException: Failed to created node environment
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:164)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:77)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:245)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
    Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:126)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:162)
	... 4 more

However, my elasticsearch is up and running.
    $ curl 'http://localhost:9200/?pretty'

    {
      "status" : 200,
      "name" : "Rom the Spaceknight",
      "cluster_name" : "elasticsearch",
      "version" : {
        "number" : "1.6.0",
        "build_hash" : "cdd3ac4dde4f69524ec0a14de3828cb95bbb86d0",
        "build_timestamp" : "2015-06-09T13:36:34Z",
        "build_snapshot" : false,
        "lucene_version" : "4.10.4"
      },
      "tagline" : "You Know, for Search"
    }

 I'm not sure this will not trigger some unattended error once openPass is deployed, I'll check it, but maybe the test should be adapted to consider this configuration

EDIT
-------
The last test also fails, I don't know if it is related with the previous one

    $ grunt elasticsearchIndexUsersSettings
        Running "elasticsearchIndexUsersSettings" task
        Fatal error: connect ECONNREFUSED

**Comment by kewisch** [comment]
The grunt midway tests are starting their own elasticsearch instance. It looks to me like they are trying to use the data dir from your system elasticsearch, and failing due to permissions. Just for testing, can you stop your system elasticsearch, and run the grunt test as root?

**Comment by rpignolet** [comment]
I do not test with Elasticsearch 1.6, for now we are using ES 1.3.5, MongoDB 2.6.5 and the MongoDB-river 2.0.2.
With an installation into the system (with apt-get) I have also the logging issue so I install ES with the `tar.gz` here: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.3.5.tar.gz.

I suggest that you remove the ES of your system, use the `tar.gz` version by using the ENV variable `CMD_ELASTICSEARCH` like this:

```
export CMD_ELASTICSEARCH=/path/to/your/es/elasticsearch-1.3.5/bin/elasticsearch
grunt test --chunk 1
```

**Comment by sieira** [comment]
@kewisch I get the same result :

    $ sudo service elasticsearch stop

Then running the
    sudo grunt shell:elasticsearch

it fails the same way

Actually, whenever I try to launch 
    $ elasticsearch

from my commandline, I get the same stack. Apparently /usr/share/elasticsearch/config doesn't exist. I will test with 1.3.5

**Comment by rpignolet** [comment]
Do not forget that once you have uncompress ES you must run `/path/to/your/es/bin/plugin --install com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/2.0.2` because test suite do not install the river.

**Comment by sieira** [comment]
I tried 1.3.5 and it passes the test (without uninstalling the former version, nor installing the river, actually)

    Running "shell:elasticsearch" (shell) task
    >> Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
    Elasticsearch server is started.
    Done, without errors.
.

    grunt test --chunk 1

Failed with 7 issues related to the user domain module.

Just in case I uninstalled and purged elasticsearch 1.6 and installed the river on 1.3.5

Then, the tests failed on the mongo-based authentication module as well.

Since the tests didn't stop, I guess this was meant to happen, ain't it?

npm start works without problems, I can go through the mongodb connection form and get to the homepage, but trying to register an user gives me this warning:

    warn: Signup invitation have not been sent Mail transport is not configured

I suppose those are completely different problems, I'll try to figure out how to go on from here.

Thank you for your kind assistance

P.S: Voici le résultats des test

>>    147 passing (2m)
>>    8 failing
>> 
>>   1) The mongo-based authentication module should not auth from invalid email:
>>      Uncaught AssertionError: expected { Object ($__, isNew, ...) } to be false
>>    2) The user domain module Basics tests (list users) should return the users which belong to a domain and which contain the search term:
>>       Error: timeout of 20000ms exceeded
>>        at null.<anonymous> (/home/luis/openpaas/rse/node_modules/mocha/lib/runnable.js:139:19)
>>       at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
>> 
>>   3) The user domain module Tests cases (search users) "before all" hook:
>>      Error: timeout of 20000ms exceeded
>>       at null.<anonymous> (/home/luis/openpaas/rse/node_modules/mocha/lib/runnable.js:139:19)
>>       at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
>> 
>>   4) The user domain module Tests cases (search users) "after all" hook:
>>      Error: Trying to open unclosed connection.
>>       at NativeConnection.Connection.open (/home/luis/openpaas/rse/node_modules/mongoose/lib/connection.js:210:15)
>>       at Mongoose.connect (/home/luis/openpaas/rse/node_modules/mongoose/lib/index.js:212:15)
>>       at Context.<anonymous> (/home/luis/openpaas/rse/test/unit-storage/core/user/domain.js:181:21)
>>        at Hook.Runnable.run (/home/luis/openpaas/rse/node_modules/mocha/lib/runnable.js:196:15)
>>       at next (/home/luis/openpaas/rse/node_modules/mocha/lib/runner.js:259:10)
>>       at Object._onImmediate (/home/luis/openpaas/rse/node_modules/mocha/lib/runner.js:276:5)
>>       at processImmediate [as _immediateCallback] (timers.js:330:15)
>> 
>>   5) The user domain module Tests cases extra (search users) "before all" hook:
>>      Error: timeout of 20000ms exceeded
>>       at null.<anonymous> (/home/luis/openpaas/rse/node_modules/mocha/lib/runnable.js:139:19)
>>       at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
>> 
>>   6) The user domain module Tests cases extra (search users) "after all" hook:
>>      Error: Trying to open unclosed connection.
>>       at NativeConnection.Connection.open (/home/luis/openpaas/rse/node_modules/mongoose/lib/connection.js:210:15)
>>       at Mongoose.connect (/home/luis/openpaas/rse/node_modules/mongoose/lib/index.js:212:15)
>>       at Context.<anonymous> (/home/luis/openpaas/rse/test/unit-storage/core/user/domain.js:425:21)
>>        at Hook.Runnable.run (/home/luis/openpaas/rse/node_modules/mocha/lib/runnable.js:196:15)
>>       at next (/home/luis/openpaas/rse/node_modules/mocha/lib/runner.js:259:10)
>>       at Object._onImmediate (/home/luis/openpaas/rse/node_modules/mocha/lib/runner.js:276:5)
>>       at processImmediate [as _immediateCallback] (timers.js:330:15)
>> 
>>   7) The user domain module Community tests "before all" hook:
>>      Error: timeout of 20000ms exceeded
>>       at null.<anonymous> (/home/luis/openpaas/rse/node_modules/mocha/lib/runnable.js:139:19)
>>       at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
>> 
>>   8) The user domain module Community tests "after all" hook:
>>      Error: Trying to open unclosed connection.
>>       at NativeConnection.Connection.open (/home/luis/openpaas/rse/node_modules/mongoose/lib/connection.js:210:15)
>>       at Mongoose.connect (/home/luis/openpaas/rse/node_modules/mongoose/lib/index.js:212:15)
>>       at Context.<anonymous> (/home/luis/openpaas/rse/test/unit-storage/core/user/domain.js:581:21)
>>       at Hook.Runnable.run (/home/luis/openpaas/rse/node_modules/mocha/lib/runnable.js:196:15)
>>       at next (/home/luis/openpaas/rse/node_modules/mocha/lib/runner.js:259:10)
>>       at Object._onImmediate (/home/luis/openpaas/rse/node_modules/mocha/lib/runner.js:276:5)
>>       at processImmediate [as _immediateCallback] (timers.js:330:15)
>> 
>> 
>> 
>> Warning:  Use --force to continue.
>> 
>> Aborted due to warnings.
>> 
--> failed "Gruntfile-tests.js" (140227ms)
--> failed all_with_storage @ "Gruntfile-tests.js"

Warning: 1 gruntfile failed and completed 0 (140230ms)

**Comment by rpignolet** [comment]
Are you using a MongoDB version 2.6.X ?

For register error it is "normal" because you do not put the mail configuration.
You must put in collection `configuration` this object:

```
{
  "_id": "mail",
  "mail": {
    "noreply": "noreply@open-paas.org"
  },
  "transport": {
    "module": "nodemailer-browser",
    "config": {
      "dir": "/tmp",
      "browser": true
    }
  }
}
```

**Comment by sieira** [comment]
I am

    $mongod --version
    db version v2.6.3
    2015-07-08T16:48:56.350+0200 git version: nogitversion
    2015-07-08T16:48:56.350+0200 OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
The one from the ubuntu universe repo

    $ apt-cache madison mongodb
    mongodb | 1:2.6.3-0ubuntu7 | http://fr.archive.ubuntu.com/ubuntu/ vivid/universe amd64 Packages

I'll test the mail configuration later, I have an appointment now. Thanks again
