### ISSUE TITLE
Error Docker-Compose Mongo

### ISSUE THREAD

**Issue by cedric190985** [linagora/openpaas-esn#15]
When I try to deply OpenPaaS with docker, I have this error. 

```
Status: Downloaded newer image for linagora/james-project:latest
Creating platform_redis_1
Creating platform_elasticsearch_1
Creating platform_james_elastic_1
Creating platform_mongo_1
Creating platform_cassandra_1
Creating esn_james

ERROR: for mongo  driver failed programming external connectivity on endpoint platform_mongo_1 (27e46dee179f84f1656a97f0bb8eabe3f9cdd3bd0d2111d5dba819a35e82cc22): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'
```

Linux Ubuntu 16.04
docker-compose 1.7.1

**Comment by strokyl** [comment]
This mean you already have a program listening on this port. I would guess, you have a mongo instance running. You can check that yes `sudo systemctl status mongod.service`. If yes, you can stop the service with `sudo systemctl stop mongod.service`.
If this is not that, you can find the program behind the port 27017 using netcat `sudo netstat -tulpn | grep 27017` then you can kill it with his PID using the command kill.

**Comment by cedric190985** [comment]
Great
I am killing MongoDB service

**Comment by cedric190985** [comment]
I close this Issue

**Comment by strokyl** [comment]
You don't need to rebuild openpaas, just rerun docker-compose.
