### ISSUE TITLE
Cannot log in with Open-paas following the official guides

### ISSUE THREAD

**Issue by emil-simeonov** [linagora/openpaas-esn#18]
Hi,

First of all, congratulations on the fine project. Open-paas seems to be fresh breeze in the FOSS ESN domain.

I followed the instructions published here:
https://github.com/linagora/openpaas-esn/blob/master/docker/doc/run.md

Yet I ran in a peculiar issue. You will find a step by step report below and I hope that you will be able to help me overcome it.

1. I got open-paas up and running in docker and I managed to navigate to the login page (http://localhost:8080).
2. I created a new domain, but honestly I will use the default one for the sake of this issue description.
3. I added a user to the new domain.
```
docker exec esn_james java -jar /root/james-cli.jar -h localhost adduser emsi@open-paas.org password
adduser command executed sucessfully in 418 ms.
adduser command executed sucessfully in 418 ms.
```
4. Tried to log in using telnet.
```
telnet localhost 1143
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
* OK JAMES IMAP4rev1 Server  Server open-paas.org is ready.
A0 LOGIN emsi@open-paas.org password
A0 OK LOGIN completed.
```
5. Tried to log in with this same user via the web frontend.

**Expected result**
Log in with the system.

**Actual result**
I am always prompted to check my credentials and not allowed to log in.

**Notes**
I noticed the following message in my terminal:
```
esn              | error: Problem while setting login failure for user emsi@open-paas.org Error: No such user emsi@open-paas.org
esn              |     at /var/www/backend/core/user/login.js:40:23
esn              |     at Query.<anonymous> (/var/www/node_modules/mongoose/lib/model.js:3336:16)
esn              |     at /var/www/node_modules/kareem/index.js:259:21
esn              |     at /var/www/node_modules/kareem/index.js:127:16
esn              |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
esn              |     at process._tickCallback (internal/process/next_tick.js:98:9)
```
Thank you in advance.

**Comment by thomas-hilaire** [comment]
Hello,

You are adding a user to the mail server only (esn-james is the mail server).
By following the run.md document, you should have set the PROVISION=true parameter while running the docker command, this has for effect to create some users for you.

Did you try to log with "admin@open-paas.org" with the password "secret" ? You should also have user1, user2, etc on the same domain, and the same password.

Thanks for your detailed report!

**Comment by emil-simeonov** [comment]
Thank you for your help. I managed to log in with the system by using the aforementioned user's e-mail address and the 'secret' password. :-)
