### ISSUE TITLE
How can I activate the Communities module

### ISSUE THREAD

**Issue by emil-simeonov** [linagora/openpaas-esn#19]
Hi,

I am sorry, if my question would be a stupid one, but I watched few videos on your youtube channel. Some of them were demonstrating some awesome features on working with Communities. How could I find and activate the corresponding module/application?

Thank you in advance.

**Comment by MichaelBailly** [comment]
Hello,

The community module is enabled, although hidden. You have to point your browser to the /communities URL to access it (https://your.instance/#/communities ).

Regards

**Comment by emil-simeonov** [comment]
Thank you. This worked perfectly well for me.
