### ISSUE TITLE
Roadmap in terms of timelines

### ISSUE THREAD

**Issue by emil-simeonov** [linagora/openpaas-esn#20]
Dear openpaas-esn team,

I managed to deploy openpaas-esn using Docker and I am fascinated with the way you managed to design and architect the foundation of this admirable initiative.

Yet the system currently does not expose user accessible features (applications/modules) that would help covering huge number of end-to-end scenarios that one could imagine as part of the typical ESN usage.

I also quickly went through the future features that you had planned on http://open-saas.org. Would you shed some lines how you would deliver these in terms of some relative timelines? Do you have some principal release schedue that I could keep in mind and follow up upon? 

Thank you in advance for sharing some details.

**Comment by MichaelBailly** [comment]
Hello,

Thanks for this really nice message ! Regarding the roadmap: we intend to ship our MVP version on February. It will concentrate on the webmail/calendars/addressbooks modules. You seem to have lots of ideas regarding OpenPaaS, maybe you can share some of your ideas ?

Cheers
Michael

**Comment by emil-simeonov** [comment]
Hi Michael, all,

Thanks for the quick and informative reply. Yes, I have some ideas that could be important for OpenPaas. I will share some of them as user stories, so they could be discussed one by one:

**The most important requirements from my humble early adopter's perspective**

1. As an IT Operations manager I would like to be able to configure OpenPaas in a way that Single Sign On with it is supported.
2.  As an IT Operations manager I would like to have the following guides present in order to be able to plan, deploy, configure, support and maintain OpenPaas as the company  ESN
- Sizing guide describing the typical system requirements necessary to develop, test and deploy OpenPaas in production scenarios (great if there would be some guidance based on number of users, concurrent users, volume of stored documents, etc.)
- Basic ALM guide (install and update with minimal downtime)
- Integration guide describing LDAP and other integrations
- Basic security guide, so I could plan for deploying and maintaining OpenPaas as part of my company infrastructure.
3. As a Corporate Marketing Manager I would like to be able to whitelist OpenPaas so that it fits well our corporate identity (CI), which as minimum would mean easily changing the logo image as well as the login page (for the corresponding domain) - the background image and content. From there on it would be great to be able to modify the whole theme in some user friendly way.
4. As a Corporate Marketing Manager I would like to be able to define (customize) a sensible Home page out of a template one for the whole organization. Employees shall be navigated to it by pressing the logo button. 
5. As an employee I would like to search for titles/names of document files and comments in Communities.
6. As an employee I would like to have some (media) preview of the links and attachments that I post as part of my comments in Communities.

We could use OpenPaas for serving as our company ESN solution, when such features/documents would be available.

**Nice to have features**
1. As an employee I would like to easily search for uploaded documents (that I have permissions to access), incl. search in the content of typical text files.
2. As an employee involved in project work I would like to be able to
- Easily create JIRA (and Trello, and what not) issues directly from OpenPaas
- Map OpenPaas communities to user stories/issues in JIRA (so that results from comments and polls are reflected in JIRA as comments), so they could facilitate transparent and collaborative decision making.
3. As a OpenPaas administrator I need a way to easily define roles and associate permissions for them.
4. As a Corporate Marketing Manager I need the ability to organize designated team/org/project spaces, such as: News, Compensation & Benefits, Learning & Development, Report Center, etc.
5. As an employee I would highly appreciate some advanced means for defining my search criteria based on time and author, etc.
6. As an employee I would find it quite nice if OpenPaas gave me a chance to be notified on any device by integrating with some of the communication tools that I already use for work, such as Slack, Rocket.Chat, etc.
7. As an employee I would feel more motivated to share content and opinions if somehow rewarded. Company/Organizational image, appearance and recognition seem to be very important for most people, I see ;-). In this regards, some simple and extensible gamification scheme backed up by simple analytics would be really a great fit for OpenPaas.

Well, for sure one could always think of other features, such as collaborative document editing, for instance, but I would personally vote for any of the aforementioned ones before getting to this next level.

Thank you and best regards,
Emil

**Comment by tanandy** [comment]
hi guys, we plan to change some part of openpaas and also work more closer with our new open source product https://twake.app/
since this is very old, and we plan to publish roadmaps in the future i close this one.
stay tune
