### ISSUE TITLE
Maximum POST size accepted by module's backend

### ISSUE THREAD

**Issue by BDan** [linagora/openpaas-esn#21]
Dear openpaas-esn team,
 
While developing an OpenPaaS module I hit an issue: maximum length of a JSON message accepted by a module’s backend via HTTP POST is limited to 100kb. 
 
This can be overcome by modifying the file [backend/webserver/application.js](https://github.com/linagora/openpaas-esn/blob/master/backend/webserver/application.js) in line 32 from 
`application.use(bodyParser.json()); `
 to
 `application.use(bodyParser.json({limit:'5mb'}));`
 
I’m not aware of any solution to this issue which can be applied from the module itself, without modifying the core OpenPaaS. Do you have any advices regarding this?
 
Best regards,
--Dan Bendas

**Comment by abenchi** [comment]
Hello Dan Bendas,

We are happy to know that you are using our lovely OpenPaaS. Regarding your question about the JSON limit, I think that your suggested solution is fair enough. 

We are going to deal with this small issue, and we will informed you once it is fixed.

Regards
