### ISSUE TITLE
Check current User on open-paas own module 

### ISSUE THREAD

**Issue by DavidAleixo** [linagora/openpaas-esn#22]
Hi there,

I am trying to develop one open-paas module. This module is already up and running - however in order to present relevant information based on which user is accessing it, I need to check the current user logged in on the open-paas. 
How can I get this user information on my own module?

Thank you,
David

**Comment by chamerling** [comment]
Hi,

For now you can get the user in the express request if it is an HTTP call, so in req.user.

**Comment by chamerling** [comment]
Hi @DavidAleixo,

Is it OK, can we close?

**Comment by DavidAleixo** [comment]
Yes please.

Thank you,
David Aleixo
