### ISSUE TITLE
Components folder missing

### ISSUE THREAD

**Issue by Emibrown** [linagora/openpaas-esn#23]
when trying to run openpass here is the error i received 

error: Less compilation failed: 
{ [Error: '../components/material-admin/less/inc/less-plugins/for.less' wasn't found. Tried - /home/emibrown/Videos/openpaas-esn-master/frontend/components/material-admin/less/inc/less-plugins/for.less,../components/material-admin/less/inc/less-plugins/for.less]

it clear that the component folder is missing
please how can i fix this

**Comment by heroandtn3** [comment]
Hi @Emibrown, try `bower install`, it should fix your problem

**Comment by Emibrown** [comment]
ok thank it works but am having another problem on the  setup page

here is what i have

**Comment by chamerling** [comment]
Hi @Emibrown,

What problem do you have now?
You can bypass the settings page by defining your own database configuration file in config/db.json like:

```
{"connectionOptions":{"db":{"w":1,"fsync":true,"native_parser":true},"server":{"socketOptions":{"keepAlive":30000,"connectTimeoutMS":30000},"auto_reconnect":true,"poolSize":10}},"connectionString":"mongodb://0.0.0.0:27017/esn"}
```

Update the mongo connection string to match your instance and restart.

**Comment by Emibrown** [comment]
am i to create this config/db.json or they is already an existing one
because i can fine db.json in config folder

**Comment by Emibrown** [comment]
alright it coming up now but how can i get the username and password

**Comment by Emibrown** [comment]
Please is they no other way i can properly  run openpaas-esn locally on my computer with out using docker

**Comment by tanandy** [comment]
hello at this time, we are changing things. we basically run docker images you are right and will study the possibility to deploy package in another way in the future.
