### ISSUE TITLE
libgif-dev (dépendance manquante)

### ISSUE THREAD

**Issue by GuillaumeDesforges** [linagora/openpaas-esn#29]
Bonjour,

il manque `libgif-dev` dans les dépendances ( `sudo apt-get install libgif-dev` ) dans le 3 du guide https://github.com/linagora/openpaas-esn/blob/master/docker/doc/install.md

Sinon un `make` du `npm install` fail.
Sur Linux Mint 18

**Comment by tanandy** [comment]
hi thank you for your feedback, we plan to change and update documentation in the future.
stay tune
