### ISSUE TITLE
docker compose en sudo

### ISSUE THREAD

**Issue by GuillaumeDesforges** [linagora/openpaas-esn#30]
Dans le guide install.md pour docker, vous proposez d'utiliser 

```ESN_HOST=<YOUR_ESN_IP> ESN_PATH=$PWD docker-compose -f ./docker/dockerfiles/dev/docker-compose.yml up```

Ce qui suppose que l'utilisateur est soit _root_, soit dans le groupe _docker_. Etre en _root_ est connu pour être une mauvaise idée (cela reste un choix) et dans la plupart des cas je ne sais pas si cela sera le cas des utilisateurs. Si l'utilisateur est dans le groupe docker, c'est peut-être pire car il ne connaît peut-être pas la faille de sécurité : https://fosterelli.co/privilege-escalation-via-docker.html

Je vous propose de passer cette ligne en _sudo_ :

```ESN_HOST=<YOUR_ESN_IP> ESN_PATH=$PWD sudo docker-compose -f ./docker/dockerfiles/dev/docker-compose.yml up```

**Comment by heroandtn3** [comment]
Same as #31, you can follow the new instruction here http://docs.open-paas.org/getting-started/docker/
