### ISSUE TITLE
Create : Designing and editing documents with OpenPaaS

### ISSUE THREAD

**Issue by lecoqnicolas** [linagora/openpaas-esn#33]
Advertised on your open-paas.org webpage, the writer/spreadsheet/presentation features look absent from the OpenPaaS work environment that loads with docker.

Are these features antive and still under development? Or is it a third-tier extension, accessed through a callback URLs under the "Applications" Menu? (Then, which URL?)

**Comment by chamerling** [comment]
We have a prototype based on onlyoffice for this. This is planned to be delivered as a module later this year.

**Comment by lecoqnicolas** [comment]
In that case, can you please keep me up to date?

Thanks.

**Comment by chamerling** [comment]
The easiest way to be informed if to follow the project on https://twitter.com/awesomepaas

**Comment by rhclayto** [comment]
I am wondering if any progress has been made on incorporating an OnlyOffice installation into OpenPaas. This is something I would miss if i were to migrate away from Nextcloud, which has an OnlyOffice app.

**Comment by tanandy** [comment]
thank you for your feedback guys. we support it directly through on our new opensource production and some news changes are coming : https://twake.app/
