### ISSUE TITLE
Error naming package in openpaas-davserver on Debian Stretch

### ISSUE THREAD

**Issue by rican13** [linagora/openpaas-esn#40]
Hello the package "openpaas-davserver" contains a dependency error!
This is the package "php-mongo" which is really called "php-mongodb". 
This error blocks the installation on Debian Stretch. 
Could you make a correction as soon as possible.
Cordially.

**Comment by tuanlc** [comment]
Hello,
Thank you for your feedback.
We correcting it and tell you as soon as possible when it is solved.
