### ISSUE TITLE
ERROR Command "init"

### ISSUE THREAD

**Issue by sotoplatero** [linagora/openpaas-esn#42]
In fresh install in debian stretch when I run
_opctl init --email admin@openpaas.local_

and fire error

_[CLI] ERROR Command "init" returned an error: Error: Incorrect HTTP method for uri [/real.core.events.idx?type=core.events] and method [POST], allowed: [GET, PUT, DELETE, HEAD]_

**Comment by tanandy** [comment]
sorry for late support, we plan to change new things and openpaas architecture.

stay tune
