### ISSUE TITLE
Administrator user can not change default users password

### ISSUE THREAD

**Issue by kolisayeed** [linagora/openpaas-esn#44]
I install openpaas-esn on Debian via script. 
apt-get install -y openpaas openpaas-davserver openpaas-james.
opctl init --email admin@example.com
opctl platformadmin init --email admin@example.com

Login with administrator privilege
admin
admin.

Then create an user:   demouser@example.com
and Try to change  demouser@example.com's password. But no found user's password change option.

And demouser@example.com can login via web.  but can not add this user_id on Thunderbird. 
Error:  Configuretion could not be verified-is the username or password wrong?

What is my wrong?
Please help me

**Comment by tuanlc** [comment]
Hello @kolisayeed 

For now, OpenPaaS does not allow domain administrator to change domain members password

Regarding the Thunderbird issue, can you give me your configuration when you adding the demo user?

**Comment by kolisayeed** [comment]
Thank You.
Thunderbird configuration:

Your name: Demo User
Email address: demo.user@example.com
Password: **********
Check: Remember password

Configuration Found by Trying common server names

Incoming: IMAP, mail.example.com, STARTTLS
Outgoing: SMTP, mail.example.com, STARTTLS
Username: demo.user

Manual Config:
Incoming: IMAP, mail.example.com, 143  STARTTLS  Normal password
Outgoing: SMTP, mail.example.com, 25 STARTTLS    Normal password
Username: Incoming  demo.user                 Username: Outgoing  demo.user

Click Done 
Configuretion Could not be verified-is the username or password wrong?

Click Re-test:
The following settings were found by probing the given server

Then Click Done:
Configuretion Could not be verified-is the username or password wrong?


What is solve?

**Comment by tuanlc** [comment]
Hi,
When you create a user via James command line, that means the user is already created in James.

But when you create a user via OpenPaaS administration center, the user is not created at James side yet. That why Thunderbird cannot add this user.

To make the user really create at James side, login to OpenPaaS as his account.

**Comment by tuanlc** [comment]
Hi @kolisayeed ,
Did you solve the issue?
