### ISSUE TITLE
Openpaas-esn installation problem on Ubuntu 16.04

### ISSUE THREAD

**Issue by kolisayeed** [linagora/openpaas-esn#46]
Ubuntu-16.04

I install: 
ElasticSearch v2.3.2
MongoDB v2.6.5
Redis 3.x
RabbitMQ 3.6.x
node version: v8.11.4

openpaas-esn_path: /root/openpaas-esn
esn-sabre_path: /var/www/html/esn-sabre

composer update successful

/var/www/html/esn-sabre/config.json

{
  "webserver": {
    "baseUri": "/",
    "allowOrigin": "*",
    "realm": "ESN"
  },
  "amqp": {
    "host": "localhost",
    "port": "5672",
    "login": "guest",
    "password": "guest"
  },
  "database": {
    "esn": {
      "db": "esn",
      "connectionString" : "mongodb://127.0.0.1:27017/",
      "connectionOptions": {
        "w": 1,
        "fsync": true,
        "connectTimeoutMS": 10000
      }
    },
    "sabre": {
      "db": "sabre",
      "connectionString" : "mongodb://127.0.0.1:27017/",
      "connectionOptions": {
        "w": 1,
        "fsync": true,
        "connectTimeoutMS": 10000
      }
    }
  },
  "esn": {
    "apiRoot": "http://192.168.100.1:8080",
    "calendarRoot": "http://192.168.100.1:8080/calendar/api"

http://192.168.100.1/esn-sabre/esn.php

<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.2.0</s:sabredav-version>
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>File not found: esn-sabre in 'root'</s:message>
<s:file>
/var/www/html/esn-sabre/vendor/sabre/dav/lib/DAV/SimpleCollection.php
</s:file>
<s:line>91</s:line>
<s:code>0</s:code>
<s:stacktrace>
#0 /var/www/html/esn-sabre/vendor/sabre/dav/lib/DAV/Tree.php(68): Sabre\DAV\SimpleCollection->getChild('esn-sabre') #1 /var/www/html/esn-sabre/vendor/sabre/dav/lib/DAV/Tree.php(71): Sabre\DAV\Tree->getNodeForPath('esn-sabre') #2 /var/www/html/esn-sabre/vendor/sabre/dav/lib/DAV/CorePlugin.php(81): Sabre\DAV\Tree->getNodeForPath('esn-sabre/esn.p...') #3 [internal function]: Sabre\DAV\CorePlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) #4 /var/www/html/esn-sabre/vendor/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array) #5 /var/www/html/esn-sabre/vendor/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:GET', Array) #6 /var/www/html/esn-sabre/vendor/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) #7 /var/www/html/esn-sabre/esn.php(238): Sabre\DAV\Server->exec() #8 {main}
</s:stacktrace>
</d:error>

In which Folder or file will be the following entry to enable CalDAV support in openpaas-esn?
{
        "_id" : "davserver",
        "backend" : {
                "url" : "http://192.168.7.6/esn-sabre/esn.php" // replace 192.168.7.6 by your localhost
        },
        "frontend" : {
                "url" : "http://my-caldav-server.example.com/esn-sabre/esn.php"  // replace my-caldav-server.example.com by your localhost
        }
}

if I command 
make test

Output show:
/var/www/html/esn-sabre/tests/DAV/ServerMock.php:224
/var/www/html/esn-sabre/tests/JSON/PluginTest.php:19

242) ESN\JSON\PluginTest::testAddressBookACLShouldReturn400IfBodyIsEmpty
MongoConnectionException: Failed to connect to: mongo:27017: Previous connection attempts failed, server blacklisted

/var/www/html/esn-sabre/tests/DAV/ServerMock.php:224
/var/www/html/esn-sabre/tests/JSON/PluginTest.php:19

--

There was 1 failure:

1) ESN\CalDAV\Backend\MongoTest::testCreateSubscriptionFail
Failed asserting that exception of type "MongoConnectionException" matches expected exception "\Sabre\DAV\Exception\Forbidden". Message was: "Failed to connect to: mongo:27017: Previous connection attempts failed, server blacklisted" at

Please help me

**Comment by tanandy** [comment]
hi, we plan to provide better support in the future and we are rearchitecting things to make it simpler.
sorry again, 

stay tune
