### ISSUE TITLE
Several issues with mail/calendar/contact - report after a thorough test

### ISSUE THREAD

**Issue by samir-s** [linagora/openpaas-esn#47]
Hi,

I took a shot on openpaas, following the instruction for a full install on debian jessie. I've met several issues. 
This report would be valuable for anyone evaluating openpaas for a production environment.

Out of the box, here is the current openpaas status:
-> mail : I was unable to set up my own imap account, the doc tells nothing about that, tried several combination without success
-> contact : "something wrong" error message, does not work at all
-> calendar : unable to add an event

Overall, the interface looks nice and features promising, but the basic groupware features do not work at all. The software in its current state is not suitable for an environment production. Maybe after some tweaking I don't know about, but not out of the box.
  
My recommandation would be that instead trying to add a lot of features (communities, chat, and so on), I would focus on the basic groupware features, mail/calendar/contact trio, and make it roar. Your current strategy seems missing its target, by trying to cover too many things, you might cover nothing at the end of the day. 

However, I'm willing to test the groupware features, if you can give clear indication on how to make it work - as I said, you did a great job and I really wish you successful work on this neat project !

My 2 cents

**Comment by chamerling** [comment]
Hello @samir-s,

Thanks for your feedback, we really appreciate the time you spent to try OpenPaaS. While I am 'compiling' answers to your questions, can you tell me which version you tested (we released v1.2.0 some days ago) ?

**Comment by rouazana** [comment]
Hi,

I just tried quickly the docker-compose option that you can find here: http://docs.open-paas.org/getting-started/docker/

Concerning IMAP connection, you can try to configure your email client to connect to localhost on port 1143. You should be able to use the login/password available here: http://docs.open-paas.org/getting-started/docker/

There is also a page and even an extension to help you configure Thunderbird: http://localhost:8080/#/controlcenter/sync

**Comment by chamerling** [comment]
@samir-s,

It seems that we have a configuration issue on Linux, the `opctl` commands will fail in some cases.
What you can do, is removing the elasticsearch indexes and try again.

From your terminal:

```
curl -X DELETE "localhost:9200/real.groups.idx"
curl -X DELETE "localhost:9200/real.events.idx"
curl -X DELETE "localhost:9200/real.contacts.idx"
curl -X DELETE "localhost:9200/real.core.events.idx"
curl -X DELETE "localhost:9200/real.resources.idx"
curl -X DELETE "localhost:9200/real.users.idx"
```

Can you please report issue with logs, screenshots, anything else which will help for linux and/or docker?

**Comment by rouazana** [comment]
> Already figured that out, I was stuck with the opctl init command, but I've tried make elasticsearch reindexing and opctl init again and was able to log in. The issue I've met concerned for instance external imap settings and so forth...Just install yourself a vanilla openpaas instance by following your own instruction (openpaas docs linux debian) and you will be able to reproduce all the bugs mentionned in the original posting.

NIce, thank you for your feedback. External imap settings is not a supported feature for now. If you want to handle an external account via OpenPaaS, the straightforward way is to synchronize it with external tools for that. For a simple test, just copy/paste your emails in Thunderbird for example (connecting to both IMAP accounts at the same time). For an advanced test, you can use imapsync (https://imapsync.lamiral.info/) for example.

**Comment by samir-s** [comment]
Maybe there is a misunderstanding here, just have a look on this pic: 

![image](https://user-images.githubusercontent.com/842380/48479845-c5c1e080-e808-11e8-96a5-fa69ce47c604.png)

I've just replaced demo.openpaas.com by my own imap server: do you confirm that replacing the default demo one by our own imap server is not supported ?

**Comment by rouazana** [comment]
Oh yeah, this page is maybe misleading. It's asking you to configure autoconf (hum). That's an administration feature allowing to personalize the autoconfiguration page and plugin (and potentially to configure them to use different imap / smtp server if needed).
But this parameter is not used directly by OpenPaaS. It's only used to generate the plugin and the http://localhost:8080/#/controlcenter/sync page.

**Comment by samir-s** [comment]
> Oh yeah, this page is maybe misleading. It's asking you to configure autoconf (hum). That's an administration feature allowing to personalize the autoconfiguration page and plugin (and potentially to configure them to use different imap / smtp server *if needed*).
It's needed for my use case, do you mind tell me how to use a different imap server ?

**Comment by rouazana** [comment]
OpenPaaS mail interface is using [JMAP](https://jmap.io/) to contact the mail server. So you need a JMAP compatible server. BTW OpenPaaS uses some specific James administration interfaces for some administration features. If you need them, you'll have to stick with James.

So quick answer: it would be hard to use a different imap server. Maybe you should plan some synchronization.

Why do you need a different imap server?
