### ISSUE TITLE
Default user creation error

### ISSUE THREAD

**Issue by aioun** [linagora/openpaas-esn#48]
Dear Openpaas developers ,
I followed the installation guide at this web link  http://docs.open-paas.org/getting-started/linux/ . I am using Debian Jessie. 
But when I tried to create default user using the command:
opctl init --email admin@openpaas.local
I get this error.
[CLI] ERROR Command "init" returned an error: [invalid_alias_name_exception] Invalid alias name [core.events.idx], an index exists with the same name as the alias, with { index="real.core.events.idx" } :: {"path":"/real.core.events.idx/_alias/core.events.idx","query":{},"statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"invalid_alias_name_exception\",\"reason\":\"Invalid alias name [core.events.idx], an index exists with the same name as the alias\",\"index\":\"real.core.events.idx\"}],\"type\":\"invalid_alias_name_exception\",\"reason\":\"Invalid alias name [core.events.idx], an index exists with the same name as the alias\",\"index\":\"real.core.events.idx\"},\"status\":400}"}

Please tell me if I missed some thing.
Thanks

**Comment by chamerling** [comment]
Hello @aioun,

It seems that we have an init issue. Can you please remove all the indexes from elasticsearch (from the terminal with curl calls below) and run the opctl again?

```
curl -X DELETE "localhost:9200/real.groups.idx"
curl -X DELETE "localhost:9200/real.events.idx"
curl -X DELETE "localhost:9200/real.contacts.idx"
curl -X DELETE "localhost:9200/real.core.events.idx"
curl -X DELETE "localhost:9200/real.resources.idx"
curl -X DELETE "localhost:9200/real.users.idx"
```

**Comment by aioun** [comment]
Thanks @chamerling.

I think you forget : curl -X DELETE "localhost:9200/core.events.idx" to make it works.
I do it and now it is working.

**Comment by chamerling** [comment]
@aioun sorry for this. Nice to see that you have it finally up and running :)
