### ISSUE TITLE
Sending mail using unified inbox

### ISSUE THREAD

**Issue by aioun** [linagora/openpaas-esn#49]
Dear Openpaas developers,
I have succeed sending email via openpaas admin test over gmail but it was not possible to do the same action from unified email. I thought that unified email module uses the email configuration from admin interface but seems not. Please correct me if I am wrong.
Thanks in advance,

**Comment by renaudboyer** [comment]
Hi @aioun 
Mail configuration in Administration is used by the platform for administrative tasks only (notifications for instance).
Unified Inbox uses JMAP API provided by James to send and receive email, configuration have to be done in James.
