### ISSUE TITLE
Problèmes d'installation dans un environnement virtuel

### ISSUE THREAD

**Issue by laurenthdl** [linagora/openpaas-esn#5]
Bonjour, 
je tente d'installer sur une VM et j'ai quelques soucis avec la méthode indiquée.
J'ai installé tout ce qui était demandé. J'ai même installé via nvm un certain nombre d'autres modules pour coller à la version 0.10.36.
Mais j'ai encore une erreur au lancement de l'application rse.

Pourriez-vous me dire ce qu'il me faut faire ?

> linagora-rse@0.0.0 start /home/openpaas/rse
> node server.js

Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
debug: local/SUBSCRIBE to redis:configurationAvailable
debug: local/SUBSCRIBE to mongodb:connectionAvailable
debug: local/SUBSCRIBE to mongodb:connectionAvailable
debug: local/SUBSCRIBE to mongodb:connectionAvailable
debug: local/SUBSCRIBE to mongodb:connectionAvailable
debug: local/SUBSCRIBE to webserver:mongosessionstoreEnabled
debug: local/SUBSCRIBE to mongodb:connectionAvailable
error: Fatal error: Error: Cannot find module 'juice'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/openpaas/rse/node_modules/email-templates/lib/main.js:16:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Error: Cannot find module 'juice'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/openpaas/rse/node_modules/email-templates/lib/main.js:16:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! linagora-rse@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the linagora-rse@0.0.0 start script.
npm ERR! This is most likely a problem with the linagora-rse package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls linagora-rse
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/home/openpaas/.nvm/v0.10.36/bin/node" "/home/openpaas/.nvm/v0.10.36/bin/npm" "start"
npm ERR! cwd /home/openpaas/rse
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/openpaas/rse/npm-debug.log
npm ERR! not ok code 0

**Comment by sieira** [comment]
On dirait que mongoose a oublié d'installer ses dépendances. Comment avez-vous installé mongoose?

[Ceci](http://stackoverflow.com/questions/28651028/cannot-find-module-build-release-bson-code-module-not-found-js-bson) pourrait vous être utile

**Comment by MichaelBailly** [comment]
Hello,

the npm modules installation seems broken. Can you try:

    cd /home/openpaas/rse/node_modules/email-templates/
    rm -rf node-modules
    npm install

and then restart the server. That should fix your problem.

**Comment by laurenthdl** [comment]
Merci pour la réponse rapide.
mongoose est maintenant installé, mais les problèmes subsistent.

La procédure d'installation avec une version donnée de node.js complique un peu la donne. L'utilisation de nvm explique peut-être cela.

J'ai du installer les modules : 
  * node.extend 
  * mkdirp 
  * qs
  * json-stringify-safe
  * mime
  * forever-agent
  * node-gyp juice

Au niveau système, j'ai du installer : 
  * libgif-dev
  * libjpeg62-dev
  * libpangocairo-1.0-0
  * libghc-pango-dev
  * libcairo2-dev
  * freetype2-demos
  * pkg-config

Je voulais faire un rapport d'installation final.

**Comment by laurenthdl** [comment]
Thanks for quick reply.
Will try and do that.
Is there something to do for redis ? since when restarting, everything in Redis will be lost ?

Friendly.

**Comment by MichaelBailly** [comment]
redis is only used for the nodejs server to communicate with each others, in a cluster setup. It's perfectly fine to not have any persistent storage for it.

**Comment by laurenthdl** [comment]
Thanks.

**Comment by scolsonlinagora** [comment]
@laurenthdl  Is it ok now ? Can we close this issue ?
