### ISSUE TITLE
local ip access to openpaas

### ISSUE THREAD

**Issue by aioun** [linagora/openpaas-esn#55]
Dear Openpaas Developers,
I have OpenPaas installed on Debian Jessie. I can access to openpaas via the following urls:
http://openpaas.local
http://localhost:8080
http://127.0.0.1:8080 
but no way to access it via http://192;168.144.169:8080  ( a local ip of my machine).
I tried different things like routing, etc/hosts but ne way to get it work.
My question, is there any configuration in NGINX or Openpaas that I should change.
Thanks

**Comment by tuanlc** [comment]
Hello,
Firstly, hope you point to correct URL: http://192;168.144.169:8080 => http://192.168.144.169:8080 :smile: 

How did you access to the local ip? From the same machine or from another machine?
Can you show me your "/etc/hosts" ?

**Comment by osiztechnologies** [comment]
we have faced same issue while run IP address in another machine.

**Comment by tanandy** [comment]
hi guys, we plan to change the architecture and documentation on openpaas.

stay tune
