### ISSUE TITLE
Support for Elasticsearch 6.x

### ISSUE THREAD

**Issue by zapotah** [linagora/openpaas-esn#56]
Looking into Open-PaaS as a replacement for existing disparate FOSS collaboration systems, however, our elasticsearch cluster runs 6.6.0. Support for ES 2.4.x ended on 2018-02-28. 

This will be a showstopper unless it is addressed and i would imagine most people with production setups will not deploy an EOS/EOL version to be used for any reason.

**Comment by rouazana** [comment]
Hi, thank you for your interesting feedback.

I can confirm that we are working on ES 6 migration. We already started and the logging and metrics system is already compatible with ES 6. Next step is hopefully coming soon.

Regards,
Raphaël.

**Comment by tanandy** [comment]
Hi, thank you for your feedback. we are running ES6 on the last version of Openpaas and plan to switch to opendistro in the future.

stay tune
