### ISSUE TITLE
LinShare integration

### ISSUE THREAD

**Issue by alexcustos** [linagora/openpaas-esn#57]
Hello, I have LinShare setup based on Linagora's docker compose configuration. I also enabled JWT as described in [How to use JWT](https://github.com/linagora/linshare/blob/master/documentation/EN/configuration/how-to-use-jwt.md), and managed to request a token and query LinShare API. So I'm pretty sure I specified correct **API base path**, but I can't get `linagora.esn.linshare` module working as described in this newsletter [LinShare integration](https://medium.com/linagora-engineering/openpaas-newsletter-july-2018-e24419ce4e0e). It just appears in OpenPaaS menu and opens **Instance URL** in a new tab. The weird thing, I don't even see any related records in the browser console or log files. It looks like the module doesn't query LinShare API at all.

Could you please advise something or at least confirm that `linagora.esn.linshare` module should allow saving attachments to LinShare or maybe I should use another module.

**Comment by RockyMeadow** [comment]
Hello @alexcustos,

In the newsletter you mentioned, LinShare is integrated as a minor feature for the inbox module. Therefore, it is required to enable two modules:

- `linagora.esn.linshare` for defining the service to call LinShare API
- `linagora.esn.unifiedinbox.linshare` to utilize the service.  You can get it [here](https://github.com/linagora/linagora.esn.unifiedinbox.linshare)

If you managed to run LinShare successfully. Then after you enable `linagora.esn.unifiedinbox.linshare`, you should be able to save mail attachments to your LinShare account.

**Comment by alexcustos** [comment]
Hello @RockyMeadow, Thank you for your quick response. I updated OpenPaaS to version 1.3.7 and enabled both modules, and found LinShare Save button in place, but it refuses to save attachments with **401** error.

The issue is pretty obvious. OpenPaaS generates JWT token and queries LinShare with it, so I need to sync JWT keys, but LinShare doesn't accept OpenSSL keys generated by OpenPaaS. I tried to feed them instead of SSH, but LinShare not even started properly. Then I tried to convert public key to SSH format, but both tools `ssh-keygen` and `openssl` reject it with error `invalid format`, no matter how start and end lines look like.

Could you please let me know what format I should use.

**Comment by fmartin-linagora** [comment]
Hi,
If you install the linsharecli you will be able to manage public keys. We do not have administration interface for now.
```
# install cli
pip install linsharecli
# generate the config file for the cli
argtoolboxtool generate linshareadmcli
linshareadmcli pubkeys create --key my.rsa.key.pem linagora.esn.linshare
```
NB: Please use the latest release of LinShare 2.2.3

**Comment by alexcustos** [comment]
Hello @fmartin-linagora, Thank you very much! I updated all LinShare Docker containers and managed to import public key with `linshareadmcli` using PEM built from OpenPaaS JWT keys. Everything worked out perfectly.
