### ISSUE TITLE
What happened with ci.linagora.com?

### ISSUE THREAD

**Issue by alexcustos** [linagora/openpaas-esn#58]
I can't get access to this repository for a few days. I missed some modules that I can't find on GitHub.

**Comment by chamerling** [comment]
Hello @alexcustos,

Can you tell which modules are missing on github so we can mirror them?
Thx a lot

**Comment by alexcustos** [comment]
Hello @chamerling, Thank you for the great work! I'm looking for `linagora.esn.xwiki`, `linagora.esn.videoconference` modules, and maybe something else related to XWiki.

**Comment by chamerling** [comment]
OK so we have an issue with github mirroring these days, we are looking at the issue right now. Anyway, the xwiki module is just a link in the app menu, it should not be a blocker.

**Comment by chamerling** [comment]
Hello @alexcustos,

Mirroring is back. I added `linagora.esn.videoconference` module. xwiki one is deprecated, a new one will come soon.

**Comment by alexcustos** [comment]
@chamerling Thank you, I was able to install both VideoConference modules from GitHub without issues.
