### ISSUE TITLE
Centos install issue, Jame or Cassandra issue

### ISSUE THREAD

**Issue by VLGM** [linagora/openpaas-esn#62]
Hi,
I'm new with openpass
I try to setup an openpass test VM following http://docs.open-paas.org/getting-started/linux/
All seems to be good I can connect with my admins but everything related to james seems not working.....

Under plate-forme admin I have this message

Échec de la connection au serveur James, veuillez vérifier votre chemin d'accès pour l'API WebAdmin frontend

No TCP port related to james are opened (imap pop or smtp) :
 
[root@openpaas conf]# netstat  -nlpt
Connexions Internet actives (seulement serveurs)
Proto Recv-Q Send-Q Adresse locale          Adresse distante        Etat        PID/Program name    
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      16912/beam.smp      
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      16917/php-fpm: mast 
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      17018/mongod        
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      16918/redis-server  
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      16999/nginx: master 
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      5315/node           
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      16963/epmd          
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      16919/sshd          
tcp        0      0 127.0.0.1:7000          0.0.0.0:*               LISTEN      17261/java          
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      17161/sshd: root@pt 
tcp        0      0 127.0.0.1:7199          0.0.0.0:*               LISTEN      17261/java          
tcp        0      0 127.0.0.1:40321         0.0.0.0:*               LISTEN      17261/java          
tcp6       0      0 :::5672                 :::*                    LISTEN      16912/beam.smp      
tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN      16944/java          
tcp6       0      0 ::1:9200                :::*                    LISTEN      16944/java          
tcp6       0      0 :::80                   :::*                    LISTEN      16999/nginx: master 
tcp6       0      0 :::4369                 :::*                    LISTEN      16963/epmd          
tcp6       0      0 127.0.0.1:9042          :::*                    LISTEN      17261/java          
tcp6       0      0 127.0.0.1:9300          :::*                    LISTEN      16944/java          
tcp6       0      0 ::1:9300                :::*                    LISTEN      16944/java          
tcp6       0      0 :::22                   :::*                    LISTEN      16919/sshd          
tcp6       0      0 ::1:6010                :::*                    LISTEN      17161/sshd: root@pt 

[root@openpaas conf]# systemctl status james
● james.service - James stands for Java Apache Mail Enterprise Server! It has a modular architecture based on a rich set of modern and efficient components which provides at the end complete, stable, secure and extendable Mail Servers running on the JVM.
   Loaded: loaded (/etc/systemd/system/james.service; enabled; vendor preset: disabled)
   Active: active (running) since ven. 2019-03-15 17:56:13 CET; 11s ago
     Docs: http://james.apache.org
 Main PID: 19710 (java)
   CGroup: /system.slice/james.service
           └─19710 /usr/lib/jvm/jre-1.8.0-openjdk/bin/java -Dworking.directory=/var/lib/james -Xmx1024m -Dlogback.configurationFile=/etc/james/logback.xml -jar /usr/share/james/james-server.jar

mars 15 17:56:21 openpaas java[19710]: 17:56:21,236 |-WARN in ch.qos.logback.classic.encoder.PatternLayoutEncoder@305fd85d - Setting the "immediateFlush" property of the enclosing appender to false
mars 15 17:56:21 openpaas java[19710]: 17:56:21,239 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[LOG_FILE] - Active log file name: /var/log/james/james.log
mars 15 17:56:21 openpaas java[19710]: 17:56:21,239 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[LOG_FILE] - File property is set to [/var/log/james/james.log]
mars 15 17:56:21 openpaas java[19710]: 17:56:21,241 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [http.jmap] to DEBUG
mars 15 17:56:21 openpaas java[19710]: 17:56:21,241 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@57e1b0c - Propagating DEBUG level on Logger[http.jmap] onto the JUL framework
mars 15 17:56:21 openpaas java[19710]: 17:56:21,242 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
mars 15 17:56:21 openpaas java[19710]: 17:56:21,242 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@57e1b0c - Propagating INFO level on Logger[ROOT] onto the JUL framework
mars 15 17:56:21 openpaas java[19710]: 17:56:21,242 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [LOG_FILE] to Logger[ROOT]
mars 15 17:56:21 openpaas java[19710]: 17:56:21,243 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
mars 15 17:56:21 openpaas java[19710]: 17:56:21,244 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@458c1321 - Registering current configuration as safe fallback point

[root@openpaas conf]# systemctl status cassandra
● cassandra.service - SYSV: Starts and stops Cassandra
   Loaded: loaded (/etc/rc.d/init.d/cassandra; bad; vendor preset: disabled)
   Active: active (exited) since ven. 2019-03-15 17:55:51 CET; 40s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 19538 ExecStop=/etc/rc.d/init.d/cassandra stop (code=exited, status=1/FAILURE)
  Process: 19577 ExecStart=/etc/rc.d/init.d/cassandra start (code=exited, status=0/SUCCESS)

mars 15 17:55:33 openpaas systemd[1]: Starting SYSV: Starts and stops Cassandra...
mars 15 17:55:33 openpaas su[19586]: (to cassandra) root on none
mars 15 17:55:51 openpaas cassandra[19577]: Starting Cassandra: OK
mars 15 17:55:51 openpaas systemd[1]: Started SYSV: Starts and stops Cassandra.

And the james.log is empty .....

Is there anyone who can help me ?
Regards

**Comment by VLGM** [comment]
Hi,
The problem deals with james and cassandra :+1: 

17:08:02,989 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@458c1321 - Registering current configuration as safe fallback point

Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'

**Comment by chibenwa** [comment]
Hi @VLGM 

What version of Cassandra do you rely on?

TimeWindowCompactionStrategy was introduced in the 3.x serie. If your Cassandra has a 2.x version thn this error might be encountered.

Read here for upgrading Cassandra to 3.x: https://github.com/linagora/james-project/blob/master/upgrade-instructions.md#cassandra-3113-upgrade

Would it help you?

Cheers,

**Comment by VLGM** [comment]
Hi thanks for answer.
The versions are those provides by openpaas : 

[root@openpaas linagora.esn.videoconference]# yum list installed james* cassandra*
Modules complémentaires chargés : fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.rezopole.net
 * extras: fr2.rpmfind.net
 * updates: fr2.rpmfind.net
Paquets installés
cassandra22.noarch                                                                     2.2.8-1                                                                                             @datastax
james.x86_64                                                                           3.2.0_SNAPSHOT_openpaas_1.2.2-1                                                                     @openpaas

**Comment by rouazana** [comment]
you are right, we should depend on cassandra30 package on RedHat, we will fix that.

**Comment by ricardosaracino** [comment]
I followed this [guide](https://www.vultr.com/docs/how-to-install-apache-cassandra-3-11-x-on-centos-7
) but still getting the error running  ` /usr/lib/jvm/jre-1.8.0-openjdk/bin/java -Dworking.directory=/var/lib/james -Xmx1024m -Dlogback.configurationFile=/etc/james/logback.xml -jar /usr/share/james/james-server.jar`

**Comment by ricardosaracino** [comment]
think i should have removed the previous cassandra first 

``` shell
[root@ricardosaracino ~]# yum list | grep cassandra
cassandra22.noarch                               2.2.8-1                    @datastax
cassandra.noarch                                 3.11.4-1                   cassandra
cassandra-cpp-driver.x86_64                      2.13.0-1.el7.remi          remi
cassandra-cpp-driver-devel.x86_64                2.13.0-1.el7.remi          remi
cassandra-tools.noarch                           3.11.4-1                   cassandra
cassandra12.noarch                               1.2.19-1                   datastax
cassandra20.noarch                               2.0.17-1                   datastax
cassandra21.noarch                               2.1.15-1                   datastax
cassandra21-tools.noarch                         2.1.15-1                   datastax
cassandra22-tools.noarch                         2.2.8-1                    datastax
cassandra30.noarch                               3.0.9-1                    datastax
cassandra30-tools.noarch                         3.0.9-1                    datastax

```

**Comment by ricardosaracino** [comment]
well i had to additionally copy the config files

`cp /usr/share/openpaas/packaging/common/openpaas-james/package/etc/james/* /var/lib/james/conf/`

🤞

**Comment by ricardosaracino** [comment]
got a whole list of fixes here
https://github.com/linagora/openpaas-esn/issues/70

**Comment by tanandy** [comment]
thank you for your feedback. we plan to make better documentation in the future
