### ISSUE TITLE
big data with OpenPaaS

### ISSUE THREAD

**Issue by aioun** [linagora/openpaas-esn#63]
Dear OpenPaaS developers,
What is the best way to use big data in openpaas. Suppose I want to store big data files containing sensors data), do I use mongo of openpaas to store them? what is the drawback in this case? what solution do you propose ?
Thanks in advance,

**Comment by phandd** [comment]
Hi, thanks for your interest with OpenPaaS. Why do you want to store big data files in OpenPaaS mongo? What are you expecting OpenPaaS to do with your files?

**Comment by aioun** [comment]
Data will be stored and used by analytics algorithms to provide users with height level  information.

**Comment by chamerling** [comment]
Hello @aioun 

How do you store data when not in OpenPaaS? There is nothing blocking you by deploying your storage next to OpenPaaS then use it in your services.
