### ISSUE TITLE
Contact Permissions

### ISSUE THREAD

**Issue by fredhampton** [linagora/openpaas-esn#64]
Is there a way to control who has access to individual users contact info?
Is it possible for a user to not share their contact information or to only share with certain members or certain groups ?

Thanks

**Comment by chamerling** [comment]
Hello @fredhampton 

Currently you can "only" share complete addressbooks and not only individual contact information with other users.
To achieve this, you have to go in calendar settings, then in the delegation tab

![Capture d’écran 2019-04-16 à 10 07 58](https://user-images.githubusercontent.com/264403/56192870-a6d1af80-602f-11e9-87dc-64264f849441.png)
