### ISSUE TITLE
OpenPaas User issue after installation on AWS ec2  instance ubuntu 18.04

### ISSUE THREAD

**Issue by AMITYTHEGREAT** [linagora/openpaas-esn#66]
Hi Team,

I have installed OpenPaas on my AWS ec2 instance ubuntu 18.4  using the docker-compose.yml. I am able to login to it but after login, I am not able to access mail feature of the application.
While sending the mail nothing is happening.

Please help me out how to use the mail functionality.

![image](https://user-images.githubusercontent.com/48387966/58113075-6955d880-7c12-11e9-8bb1-96cbac6a6814.png)

**Comment by rouazana** [comment]
Hi,

Can you check the logs please?

Thanks,
Raphaël.
