### ISSUE TITLE
Redhat installation Fixes

### ISSUE THREAD

**Issue by ricardosaracino** [linagora/openpaas-esn#70]
# Red Hat Guide 

This might not be a complete list but it has all the stuff i needed to get OpenPaas working on redhat.. i will update with any other information 

```
 Static hostname: ricardosaracino.com
         Icon name: computer-vm
           Chassis: vm
    Virtualization: microsoft
  Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
            Kernel: Linux 3.10.0-957.21.3.el7.x86_64
      Architecture: x86-64
```

## Initial

```
yum erase -y postfix
yum install -y openpaas openpaas-davserver openpaas-james
```
```
systemctl enable {mongod,elasticsearch,cassandra,redis,rabbitmq-server,php-fpm,nginx,james,openpaas}
systemctl start {mongod,elasticsearch,cassandra,redis,rabbitmq-server,php-fpm,nginx,james,openpaas}
```

## Hostname
Set the target machine’s hostname using the following command:
`hostnamectl set-hostname ricardosaracino.com`

Make sure the hostname is correctly resolved locally using this command:
```
echo "127.0.0.1 ricardosaracino.com james.ricardosaracino.com dav.ricardosaracino.com " | tee -a /etc/hosts
```

## Bootstrap the installation
```
wget -qO - https://raw.githubusercontent.com/linagora/openpaas-esn/master/packaging/setup-v1.2.sh | bash
```

## Update ENV
`vi /usr/share/config/opctl-env.sh`

## Cassandra
Step 3: Install the latest stable release of Apache Cassandra
https://www.vultr.com/docs/how-to-install-apache-cassandra-3-11-x-on-centos-7
```
cat <<EOF | sudo tee -a /etc/yum.repos.d/cassandra311x.repo
[cassandra]
name=Apache Cassandra
baseurl=https://www.apache.org/dist/cassandra/redhat/311x/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://www.apache.org/dist/cassandra/KEYS
EOF
```

```
yum remove cassandra22
yum install cassandra -y
```

## Clean Cache
```
curl -X DELETE "localhost:9200/real.groups.idx"
curl -X DELETE "localhost:9200/real.events.idx"
curl -X DELETE "localhost:9200/real.contacts.idx"
curl -X DELETE "localhost:9200/real.core.events.idx"
curl -X DELETE "localhost:9200/real.resources.idx"
curl -X DELETE "localhost:9200/real.users.idx"
curl -X DELETE "localhost:9200/core.events.idx"
```

## Init
```
/usr/local/bin/opctl init --email contact@ricardosaracino.com
/usr/local/bin/opctl platformadmin init --email contact@ricardosaracino.com
```
Login is email address, password is the first part of the email _(contact in this case)_

## Edit Nginx
```
/etc/nginx/conf.d/openpaas.conf
/etc/nginx/conf.d/openpaas-davserver.conf
/etc/nginx/conf.d/openpaas-james.conf (added this from source packaging/redhat/7/openpaas-james/package/etc/nginx/conf.d/openpaas-james.conf)
```

## Copy James Config
```
cp /usr/share/openpaas/packaging/common/openpaas-james/package/etc/james/* /var/lib/james/conf/
```
**Edit domain (used for testing via telnet)**
`/var/lib/james/conf/domainlist.xml`

## Finally
`systemctl restart {james,openpaas}`

## Start Up
These need to be run at start up still
```
systemctl stop firewalld
service rabbitmq-server start
```

**Comment by fredhampton** [comment]
Thanks so much for this !!!

**Comment by ricardosaracino** [comment]
I noticed that the james config was only copying one file you need to copy all of them

`cp /usr/share/openpaas/packaging/common/openpaas-james/package/etc/james/* /var/lib/james/conf/'

**Comment by fredhampton** [comment]
How can you use imap instead of smtp option ?


Thanks

**Comment by tanandy** [comment]
@chibenwa what do you think about it ?

**Comment by tanandy** [comment]
we plan to update documentation and of course the packages. thank you for your contribution, we will add it into our documentation if needed
