### ISSUE TITLE
Customization 

### ISSUE THREAD

**Issue by fredhampton** [linagora/openpaas-esn#71]
Is there a way to change to look and feel/template for Openpass ?

Thanks !

**Comment by tuanlc** [comment]
Hi,
If your "template" term means colors, logos, then **yes**, OpenPaaS has been developing `theme` feature which allows domain admin to customize OpenPaaS theme. You can use the feature by the following steps:

- Login as domain administrator
- Go to `Administration` page
- `Theme` page

![theme](https://user-images.githubusercontent.com/7950991/61192977-66dba080-a6e2-11e9-8979-03b024052e8f.png)

**Comment by fredhampton** [comment]
Thanks so much for this !!!!!

**Comment by fredhampton** [comment]
For some reason the theme menu option is not showing up for me.
Is it hidden ?

Thanks

**Comment by tuanlc** [comment]
Which version of OpenPaaS are you using?

This feature available from version 1.5.0

**Comment by fredhampton** [comment]
I'am using version 1.6.0-dev
Do I need to add a module for this to work ?

**Comment by tuanlc** [comment]
Weird.

Do you mean `Administration` page is hidden? or `Theme` item in the sidebar is hidden?

**Comment by fredhampton** [comment]
I found the menu option !!!!
Is there any documentation for how to configure JMAP with a Docker install ?

Thanks !!!

**Comment by tuanlc** [comment]
What do you mean by `configure JMAP`? What do you want actually?

**Comment by fredhampton** [comment]
I actually meant how to configure the James from the admin panel ?


Thanks

**Comment by tuanlc** [comment]
You can go to `Administration` -> `Modules` -> `Unified Inbox` module -> Expand the item

Then you can config JMAP.

**Comment by fredhampton** [comment]
I went to Administration -> Modules -> Unified Inbox module -> and found the JMAP configuration area.
I'am new to JMAP.
Is there documentation on how to configure the JMAP section ?
Where can I find the JMAP API ?
Is this an endpoint ?
If how can I find what the end point address should be ?

Thanks for all of your help
