### ISSUE TITLE
Sub Domain Installation 

### ISSUE THREAD

**Issue by fredhampton** [linagora/openpaas-esn#72]
Is it possible to install Openpaas using a subdomain as the target machine’s hostname....something like this  "mail.foo.com" ?
If this is possible can the email domain be something like this "xxx@foo.com"

This is similar to how gmail seems to be deployed.

Thanks!!!

**Comment by tanandy** [comment]
yes this is possible. we plan to provide better documentation on how james & openpaas interact together.
