### ISSUE TITLE
OpenPaaS v1.5.0: Limit of total fields [1000] in index

### ISSUE THREAD

**Issue by alexcustos** [linagora/openpaas-esn#74]
Hello, Due to migration to OpenPaaS v1.5.0 (mainly because of Elasticsearch v6), I deployed fresh OpenPaaS instance and tried to reindex James emails from the Cassandra database. It went not bad in general, but at some point, I received a lot of exceptions
```
esn_james        | org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=Limit of total fields [1000] in index [mailbox_v1] has been exceeded]
```
Could you please suggest me the best way to work around this issue.

**Comment by alexcustos** [comment]
Sorry, I went looking into the issue before check if it's related to Elasticsearch itself. A workaround fix is pretty simple:
```
curl -H'Content-Type: application/json' \
  -XPUT http://127.0.0.1:9200/mailbox_v1/_settings \
  -d '{"index.mapping.total_fields.limit": 10000}'
```
Here are some details about the issue: https://discuss.elastic.co/t/total-fields-limit-setting/53004

**Comment by rouazana** [comment]
Thanks for your fix. As we are creating a field per header, this limit can be reached with mails with many headers. So your fix to ElasticSearch is right.

**Comment by alexcustos** [comment]
> this limit can be reached with mails with many headers

For me it was triggered mostly for very simple text emails, about a half of them were in Sent folder with very common header set. There is an example below I saved when investigated the issue. Anyway, the issue is solved for me. I left the ticket opened because I thought you probably would like to increase this limit by default because I faced the issue with a fairly small instance. But if you see nothing interesting in it, please close this ticket.

```
a UID FETCH 5 (BODY.PEEK[HEADER])

* 5 FETCH (UID 5 BODY[HEADER] {417}
To: admin@example.com
From: Aleksandr <alexcustos@example.com>
Subject: MxToolbox
Message-ID: <b8785d29-be97-0d6e-ac91-af0e2b14dc4c@example.com>
Date: Tue, 14 May 2019 08:26:56 +0300
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101
 Thunderbird/60.3.2
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="------------536F4ACC2938C52C663F29E7"
Content-Language: en

)
a OK FETCH completed.
```

**Comment by chibenwa** [comment]
Hello @alexcustos 

My team finally found the time to do a salutary work on the underlying ElasticSearch mapping indexing.

We especially addressed issues related to dynamic mapping (at the cost of representing headers with nested objects), this work can be seen here https://github.com/linagora/james-project/pull/2738

Here is the associated Apache James JIRA ticket which embed the Architecture Decision Record: https://issues.apache.org/jira/browse/JAMES-2078

Does this solves your issue?

Benoit
