### ISSUE TITLE
James server: How to disable outdated SSLv3?

### ISSUE THREAD

**Issue by alexcustos** [linagora/openpaas-esn#76]
I have a Postfix mail server with `smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3` setting and it refuses to accept emails from the latest `linagora/james-ldap-project:openpaas-1.5.0` with these records in the log file:
```
Jul 20 17:15:14 srv postfix/smtpd[13937]: SSL_accept error from mail.example.com[123.123.123.123]: 0
Jul 20 17:15:14 srv postfix/smtpd[13937]: warning: TLS library problem: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:s3_pkt.c:1498:SSL alert number 46:
Jul 20 17:15:14 srv postfix/smtpd[13937]: lost connection after STARTTLS from mail.example.com[123.123.123.123]
```
I tried to add `<useTLS>true</useTLS>` into `<smtpserver>` sections but without success. Could you please suggest how to disable outdated SSL for SMTP transport.

**Comment by chibenwa** [comment]
Hello @alexcustos ,

RemoteDelivery relies on javax.mail for transmitting outgoing email.

You can pass any additional javax.mail configuration as a parameter.

https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html provides some options that might be helpful for you: 

 - `mail.smtp.ssl.protocols`: Specifies the SSL protocols that will be enabled for SSL connections. The property value is a whitespace separated list of tokens acceptable to the javax.net.ssl.SSLSocket.setEnabledProtocols method. 
 - `mail.smtp.ssl.ciphersuites` : Specifies the SSL cipher suites that will be enabled for SSL connections. The property value is a whitespace separated list of tokens acceptable to the javax.net.ssl.SSLSocket.setEnabledCipherSuites method. 

And I also think you are going to like:

 - `mail.smtp.ssl.enable` : If set to true, use SSL to connect and use the SSL port by default. Defaults to false for the "smtp" protocol and true for the "smtps" protocol. 

You can use directly this as XML properties for the remote delivery mailet.
