### ISSUE TITLE
Mailbox part of inbound emails is case sensitive (new account is being created for each spelling)

### ISSUE THREAD

**Issue by alexcustos** [linagora/openpaas-esn#77]
The domain part of email addresses is being processed well. In that case, I can still see a mixed case in To field, but Delivered-To contains actual domain in lowercase.

The problem only with the mailbox part. The odd thing, I can even get access to those "missed" emails. I just need to specify exactly the same email when registering an account in mail clients (all clients are affected, including Thunderbird).

Please take a look at the next log records and pay attention to MessageUID.

A normal email with mailbox and domain parts in lowercase:
> esn_james        | 07:09:45.893 [INFO ] o.a.j.m.e.e.ElasticSearchListeningMessageSearchIndex - Indexing mailbox INBOX-CassandraId{id=750da130-6a56-11e9-af12-ff36d9b29dec} of user alexcustos@example.com on message MessageUid{uid=630}

An email with mailbox part in mixed case:
> esn_james        | 07:11:30.984 [INFO ] o.a.j.m.e.e.ElasticSearchListeningMessageSearchIndex - Indexing mailbox INBOX-CassandraId{id=ee1e7c80-ac4f-11e9-b853-7bebda8da6d6} of user AlexCustos@example.com on message MessageUid{uid=1}

An email with domain part in mixed case:
> esn_james        | 07:18:33.401 [INFO ] o.a.j.m.e.e.ElasticSearchListeningMessageSearchIndex - Indexing mailbox INBOX-CassandraId{id=750da130-6a56-11e9-af12-ff36d9b29dec} of user alexcustos@example.com on message MessageUid{uid=631}

**Comment by rouazana** [comment]
Hi,

This is correct regarding RFC 5321: https://tools.ietf.org/html/rfc5321#section-2.4
```
   The local-part of a mailbox MUST BE treated as case sensitive.
   Therefore, SMTP implementations MUST take care to preserve the case
   of mailbox local-parts.  In particular, for some hosts, the user
   "smith" is different from the user "Smith".
```
But I agree is not a common behavior. We should add an option to deactivate case sensitivity for user part.

Regards,
Raphaël.

**Comment by alexcustos** [comment]
> This is correct regarding RFC 5321

Sorry, but no, the system doesn't meet that RFC, because I can't create those accounts explicitly and James accepts those emails instead of rejecting them because of an unknown user. Moreover, it allows to log in with a single password but shows a different set of emails for allegedly the same user. I considered those emails as lost for a long time, so definitely, there is something wrong with the current implementation.

**Comment by rouazana** [comment]
Hi @alexcustos,

You are right, and this has been fixed here: https://issues.apache.org/jira/browse/JAMES-2949.

Regards,
Raphaël.
