### ISSUE TITLE
Documentation for OpenPaas James configuration ?

### ISSUE THREAD

**Issue by fredhampton** [linagora/openpaas-esn#78]
We have a docker development environment running on ubuntu.
We would like our users to have the ability to use the unified inbox to send and receive email.
Is this something that we would need to configure with James ?
If so is there Documentation that you can point us to ?
If this does not require configuring James can you point us in the direction of documentation that would help us to configure our user unified inboxes so that they can both send and receive email on our installation of OpenPaas ?

Thanks !

**Comment by fredhampton** [comment]
We have a docker development environment running on ubuntu.
We would like our users to have the ability to use the unified inbox to send and receive email.
Is this something that we would need to configure with James ?
If so is there Documentation that you can point us to ?
If this does not require configuring James can you point us in the direction of documentation that would help us to configure our user unified inboxes so that they can both send and receive email on our installation of OpenPaas ?

Thanks !

**Comment by alexcustos** [comment]
It's the second issue (I believe) about the same question, but I can't get what's the problem. OpenPaaS is still under heavy work in progress, but it works well (at least for me at the moment), and its documentation is clear enough to build a production instance. All docker images were built with production option enabled as well. I can't tell if it will meet your quality standards for production, but its license explains it all.

**Comment by fredhampton** [comment]
Thanks for your reply.
I'am going to document all of the issues and will add them shortly.
