### ISSUE TITLE
Docs: Recommended deployment?

### ISSUE THREAD

**Issue by Legogris** [linagora/openpaas-esn#84]
The docs only mention Docker for "trying out OpenPaaS locally" and mark the package setup as deprecated.

For the community version, what is your recommended/supported architectures for production use? Are there guidelines or recipes for running this on containers (using e.g. Kubernetes, Mesos or Nomad?)

OpenPaas looks like a great bundle of James and I'm trying to figure out if it makes sense to use the community edition as a starting point rather than setting up vanilla James.

**Comment by fredhampton** [comment]
I asked a similar question here 
https://github.com/linagora/openpaas-esn/issues/79

**Comment by tanandy** [comment]
hi guys we are running OpenPaas in production on top of Kubernetes.

we plan to update our documentation and fix it also.
we are rearchitecturing things to make it simpler and work on the integration with twake our opensource collaboration solution.
https://twake.app/

**Comment by Legogris** [comment]
@tanandy Thanks for the update! Looking forward to what comes next
