### ISSUE TITLE
Can't install: ERROR: manifest for linagora/james-project:openpaas-1.7.3 not found

### ISSUE THREAD

**Issue by netandreus** [linagora/openpaas-esn#86]
OS: Ubuntu 16.04
Trying to install using this manual: http://docs.open-paas.org/getting-started/docker/

```
# grab the open-paas github repo
git clone https://github.com/linagora/openpaas-esn.git

# go to the repo you just cloned
cd openpaas-esn

# launch it
PROVISION=true docker-compose up
```

After last command this error appears:
`ERROR: manifest for linagora/james-project:openpaas-1.7.3 not found`

**Comment by tanandy** [comment]
Hi, 

sorry for that, we plan to fix documentation and repositories.
we are working on making things simpler.

stay tune
