### ISSUE TITLE
hublin with openpaas

### ISSUE THREAD

**Issue by hoangminhtu8** [linagora/openpaas-esn#9]
I have already installed openpass successfully, but i cant find Admin page.
How can I connect Hublin with Openpass?

**Comment by chamerling** [comment]
Hi @hoangminhtu8 

There is no admin page for now in OpenPaaS. We plan to integrate Hublin into OpenPaaS soon.

Thanks

**Comment by lecoqnicolas** [comment]
Hello,

Are you close to integrating Hubl.in into OpenPaaS? 

It has been two years since the issue has been opened and the trial version of OpenPaas with docker does not feature a Hubl.in menu.

Thanks beforehand.

**Comment by chamerling** [comment]
You are right. We focused on delivering the first version of OpenPaaS but without Hublin. The integration should come later this year. We are currently working on a new Hublin version (https://github.com/linagora/hublin/tree/janus) which will be more scalable and easier to integrate

**Comment by lecoqnicolas** [comment]
OK, I will try to run it. Please keep me posted.

**Comment by tanandy** [comment]
hi, hublin has been discontinued. there is now an admin integrated with openpaas and some changes are coming in the future.

stay tune.
