### ISSUE TITLE
Smart Mail?  

### ISSUE THREAD

**Issue by teach-ed** [linagora/openpaas-esn#91]
I see on the website that you talk about AI / Smart mail, just wondering where if at all that is included in the esn modules or is this off of james itself?

https://open-paas.org/aimail/

**Comment by cheerios911** [comment]
Just wondering if this project is going legacy with the pickup of twake?  I've seen a lot of questions that just don't have answers or replies for months on end.

WHAT IS GOING ON OPENPAAS TEAM?

**Comment by rouazana** [comment]
> Just wondering if this project is going legacy with the pickup of twake? I've seen a lot of questions that just don't have answers or replies for months on end.
> 
> WHAT IS GOING ON OPENPAAS TEAM?

No, we are working hard to integrate Twake and OpenPaaS, both products are here to have a long life!

**Comment by teach-ed** [comment]
Any update on my original comment?  I left that Aug. 5

I see on the website that you talk about AI / Smart mail, just wondering where if at all that is included in the esn modules or is this off of james itself?

https://open-paas.org/aimail/

**Comment by tanandy** [comment]
hi guys sorry for late reply. we have been busy .
we are working on changing openpaas architecture and also integration with twake

> I see on the website that you talk about AI / Smart mail, just wondering where if at all that is included in the esn modules or is this off of james itself?

to answer the question, this is not yet available. we plan to use probably our https://linto.ai/ solutions and the Linagora AI team to work on that topic

stay tune
