### ISSUE TITLE
Accessing linagora CI

### ISSUE THREAD

**Issue by GrifKies** [linagora/openpaas-esn#92]
Via some of you docs on OpenPAAS, I was advised to go to your gitlab ci at ci.linagora.com. It asks me for a username and password, and I enter in the correct one for my gitlab account. However, this does not seem to allow me to see the other documentation posted there. Is this an issue on my side? Do I need to create an account specific to your CI (If so, I do not see a link to do so?)
Anything helps, and thanks for making this cool platform!

**Comment by tuanlc** [comment]
Hello @GrifKies 
`ci.linagora.com` is our internal Gitlab system. So, do not have access to it.

Could you please give me the documents & links that reference to our CI? We will correct them. Sorry for the inconvenience!

**Comment by GrifKies** [comment]
In your video conference help on you website and github docs it mentions to go there to get jitsi libraries and to see more documentation.

**Comment by tanandy** [comment]
hi thank you for your feedback. we plan to make every binaries available publicly if its not the case already
